### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/sleepy-capybara#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, you'll be added as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by jonnygrm** [comment]
👋

**Comment by sirius0503** [comment]
Live life :D

**Comment by githubteacher** [comment]
Hello! 👋

**Comment by Bara-Khrais** [comment]
Hello

**Comment by mectanner** [comment]
Hi, :wave:

**Comment by mohitspawar** [comment]
Hello !!!

**Comment by ashvinsharma** [comment]
💯

**Comment by lumaquan** [comment]
Hi super!!

**Comment by githubteacher** [comment]
:tada: @jonathangrm, @jonathangrm, @sirius0503, @Bara-Khrais, @mectanner, @mohitspawar, @ashvinsharma, and @lumaquan are now  repository collaborators. :balloon:

**Comment by AliEsmaeili** [comment]
Hello :wave:

**Comment by cjcollins** [comment]
Add Me

**Comment by deyindranil** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @AliEsmaeili, @cjcollins, and @deyindranil are now  repository collaborators. :balloon:

**Comment by hectorsector** [comment]
@githubteacher 👋

**Comment by Staedlma** [comment]
hallo

**Comment by githubteacher** [comment]
:tada: @Staedlma is now a repository collaborator. :balloon:

**Comment by chianc1** [comment]
!Hi

**Comment by illumination71** [comment]
howdy!

**Comment by githubteacher** [comment]
:tada: @chianc1 and @illumination71 are now  repository collaborators. :balloon:

**Comment by soerengeorg** [comment]
Hi

**Comment by githubteacher** [comment]
:tada: @soerengeorg is now a repository collaborator. :balloon:

**Comment by rraghavanPCG** [comment]
hi

**Comment by chianc1** [comment]
Hi

Thanks,
Christina

**Comment by githubteacher** [comment]
:tada: @rraghavanPCG is now a repository collaborator. :balloon:

**Comment by nithinnambiar** [comment]
hello

**Comment by githubteacher** [comment]
:tada: @nithinnambiar is now a repository collaborator. :balloon:

**Comment by sadashivkulthe** [comment]
can you please add me as collaborator

**Comment by githubteacher** [comment]
:tada: @sadashivkulthe is now a repository collaborator. :balloon:

**Comment by MDShahrouq** [comment]
Hi, please add me too

**Comment by githubteacher** [comment]
:tada: @MDShahrouq is now a repository collaborator. :balloon:
