### ISSUE TITLE
other alternative than git

### ISSUE THREAD

**Issue by illumination71** [githubschool/sleepy-capybara#10]
I'm unable to install git for security reason. Any other recommendation to use? I have installed GitHub desktop. Thanks.

**Comment by hectorsector** [comment]
@illumination71 if you've got GitHub Desktop installed, you can use Git Shell that comes with it for the command line portion of the class. However, not every command translate from bash (which Matt is using) to PowerShell (which is what Git Shell is using) so if you need help with following that just drop a note here.
