### ISSUE TITLE
How to go in the ~/ mode in Git Bash

### ISSUE THREAD

**Issue by chianc1** [githubschool/sleepy-capybara#11]
How to go in the ~/ mode in Git Bash

Thanks.

**Comment by chianc1** [comment]
my prompt like this
chianc1@esd-ChiangC MINGW64 /
$

**Comment by hectorsector** [comment]
That's quite alright @chianc1 -- it's just what Matt's command line looks like.

**Comment by chianc1** [comment]
So, I can do all the commands that Matt did on his prompts.

**Comment by chianc1** [comment]
Thanks.
