### ISSUE TITLE
How to setup two Github account on same Ubuntu machine

### ISSUE THREAD

**Issue by MDShahrouq** [githubschool/sleepy-capybara#12]
Hey, 
- I want to setup my personal and professional github account on same machine, so can you tell me how to do this.
- I tried by due that ssh key i was not able to figure out how to do it

**Comment by hectorsector** [comment]
@MDShahrouq there's an [Authentication guide](https://help.github.com/categories/authenticating-to-github/) in our help docs that might put you on the right path.

**Comment by MDShahrouq** [comment]
@hectorsector This really huge and messy , can you send direct process

**Comment by hectorsector** [comment]
@MDShahrouq I understand, but one solution does not fit all. The authentication guide is your best bet to really understand how authentication works. One way to do this is to add multiple remotes (you can read about remotes [here](https://github.github.io/training-manual/#_multiple_remotes)), and then set up multiple remotes with your authentication token as an environment variable in the remote URL.

**Comment by MDShahrouq** [comment]
ok sure, i will try to do so . Thank you
