### ISSUE TITLE
I can't hear Matt!!!!! HELP!!!

### ISSUE THREAD

**Issue by githubteacher** [githubschool/sleepy-capybara#2]
@hectorsector I can't hear Matt, what do I do?!?!?!

**Comment by sirius0503** [comment]
@hectorsector : No volume ,here too

**Comment by hectorsector** [comment]
@sirius0503 GoToWebinar lets you switch between phone and computer, can you try that? [This article may help](http://support.citrixonline.com/en_US/webinar/all_files/G2W050044).
