### ISSUE TITLE
chianc1's class checklist

### ISSUE THREAD

**Issue by chianc1** [githubschool/sleepy-capybara#24]
- [ ] create a file
-[] Push changes
-[] Collaborate!
-[]Merge our changes!

**Comment by githubteacher** [comment]
@chianc1 don't forget to make your checklist look like this:
`- [ ] content`

**Comment by jonnygrm** [comment]
@chianc1 added the missing spaces in your first line

**Comment by chianc1** [comment]
- [ ] create a file
- [ ] Push changes
- [ ] Collaborate!
- [ ] Merge our changes!

**Comment by chianc1** [comment]
Hi Teachers,

I set to the wrong upstream https://github.com/githugschool/github-games.git. What should I do? May I delete it?

chianc1@esd-ChiangC MINGW64 /github-games (stats-update|MERGING)
$ git remote -v
origin  https://github.com/chianc1/github-games.git (fetch)
origin  https://github.com/chianc1/github-games.git (push)
upstream        https://github.com/githugschool/github-games.git (fetch)
upstream        https://github.com/githugschool/github-games.git (push)

Thanks,
Christina
