### ISSUE TITLE
@hectorsector what's that we are gonna study today?

### ISSUE THREAD

**Issue by ashvinsharma** [githubschool/sleepy-capybara#3]

**Comment by hectorsector** [comment]
@ashvinsharma the [training manual](https://github.github.io/training-manual/) shows everything we'll be covering. Today, we'll be going up to [this section](https://github.github.io/training-manual/#_config_alias), and tomorrow we'll cover the rest.

**Comment by rraghavanPCG** [comment]
hi

**Comment by hectorsector** [comment]
@rraghavanPCG do you have a question regarding what we'll cover?
