### ISSUE TITLE
There isn’t anything to compare.

### ISSUE THREAD

**Issue by Bara-Khrais** [githubschool/sleepy-capybara#32]
@hectorsector  I am trying to add a pull request with my branch but I had this message: There isn’t anything to compare.

**Comment by hectorsector** [comment]
There's a couple of reasons this could be happening, try the following.
1. Make sure there's commits that exist on your branch ([instructions](https://github.github.io/training-manual/#_two_stage_commit))
1. Push your commits to GitHub ([instructions](https://github.github.io/training-manual/#_git_push))
1. When opening a PR, make sure the base branch is `master`, and the compare branch is your branch ([instructions](https://github.github.io/training-manual/#_pull_request))
