### ISSUE TITLE
@hectorsector

### ISSUE THREAD

**Issue by mectanner** [githubschool/sleepy-capybara#35]
Hi,
I lost. I can't seem to add my local changes to the branch. It keeps asking me for my username and password and I thought what I configured is not working.

**Comment by hectorsector** [comment]
@mectanner it's asking you after `git push` right? The username is your github username, and the password is your github password. If that doesn't work, do you have 2 factor authentication set up? If so, we'll need to set up an authentication token and I can help with that.

**Comment by mectanner** [comment]
Got it. I missed the whole pull request process though.

**Comment by mectanner** [comment]
Here is where I am at.
![screen shot 2017-05-04 at 9 55 12 am](https://cloud.githubusercontent.com/assets/2743827/25706885/c7604844-30af-11e7-96e8-5cdb85ff5633.png)

**Comment by mectanner** [comment]
I'm all set so am closing this issue.
