### ISSUE TITLE
I can not push my local file into the branch

### ISSUE THREAD

**Issue by Staedlma** [githubschool/sleepy-capybara#38]
@hectorsector
I can not push my local file into the branch, looks like connection issues...
this is what i get when using GitExtention (GUI)
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/staedlma-berlin:refs/heads/staedlma-berlin

**Comment by hectorsector** [comment]
@Staedlma did you get the cloning issue resolved then? How did it get resolved? I ask because it will help us troubleshoot this issue.

**Comment by Staedlma** [comment]
@hectorsector
I did disconnect from VPN! now the networl apears to be slow...

**Comment by Staedlma** [comment]
For now I did the work directly on the GitHub web page... That worked.
