### ISSUE TITLE
got an error while cloning

### ISSUE THREAD

**Issue by Staedlma** [githubschool/sleepy-capybara#7]
@hectorsector
C:\Program Files\Git\bin\git.exe" clone -v --recurse-submodules --progress "https://github.com/githubschool/sleepy-capybara.git" "C:/Work/0_Martin/05_Desk/###GitTraining/sleepy-capybara"
Cloning into 'C:/Work/0_Martin/05_Desk/###GitTraining/sleepy-capybara'...
fatal: unable to access 'https://github.com/githubschool/sleepy-capybara.git/': Couldn't resolve host 'github.com'
Done

Press Enter or Esc to close console...

**Comment by hectorsector** [comment]
@Staedlma I have a couple of questions that can help us troubleshoot: 
1. Are you accessing github from within a company firewall? 
1. Do you already have SSH keys set up?

**Comment by soerengeorg** [comment]
I have the same issue (same company ...) and had SSH keys already set up

**Comment by hectorsector** [comment]
If you've got SSH keys set up try cloning with SSH:

```
git clone git@github.com:githubschool/sleepy-capybara.git
```

**Comment by Staedlma** [comment]
I'm acesing frin within company firewall and dialed in via VPN
I do have SSH keys installed

**Comment by Staedlma** [comment]
I got this...

$ git clone git@github.com:githubschool/sleepy-capybara.git
Cloning into 'sleepy-capybara'...
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Staedlma** [comment]
@hectorsector
added two comment but without the "add"...

**Comment by hectorsector** [comment]
@Staedlma it seems that your company firewall has blocked access to GitHub.com -- since neither HTTPS nor SSH work, please disconnect from VPN if you are able to do that, and try then.

**Comment by Staedlma** [comment]
@hectorsector
that worked, thanks
