### ISSUE TITLE
How to create a branch?

### ISSUE THREAD

**Issue by chianc1** [githubschool/sleepy-capybara#8]
How to create a branch? I missed that part.

**Comment by hectorsector** [comment]
@chianc1 click on the branch drop down in the Code tab, and type in the branch name:

![screen shot 2017-05-04 at 9 06 11 am](https://cloud.githubusercontent.com/assets/16547949/25704810/fb0342de-30a8-11e7-9944-aab9775e7045.png)

**Comment by chianc1** [comment]
Thanks. I created a new branch.
